version: "2"
services:
  node:
    image: "node"
    user: "node"
    container_name: "node"
    working_dir: /srv/meu-app
    environment:
      - NODE_ENV=development
      - PORT=3000  
    volumes:
      - ./ignite-reactjs-desafio-03:/srv/meu-app
    ports:
      - 3000:3000
      - 3333:3333
    command: "yarn start"
