version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /srv/meu-app
    environment:
      - NODE_ENV=development
    volumes:
      - ./01-github-explorer:/srv/meu-app
    ports:
      - 3000:3000
    command: "yarn dev"
